### PR TITLE
WIP - The start of the backend API

### PR DESCRIPTION
**Pull request by Linkinlog**
Aims to:

- [x] Create a web server using Go with Chi

TODO

- [ ] Plan out full CRUD routing
- [ ] Plan out method of talking to sensors
- [ ] Implement sensor communication
- [x] Decide DB
- [x] Implement DB
- [ ] Discuss with team once frontend design has been made how to structure DB
- [ ] Implement full CRUD routing

### CODE REVIEW

**Review by mitrerogelio — APPROVED** [review]
I agree with the decision to go with chi

**Review by mitrerogelio — APPROVED** [review]
less code, less problems 😎

**Comment by Linkinlog** [comment]
Decided to aim for smaller PRs, got a MVP with the backend running using Chi and will decide more direction as we go.

**Review by mitrerogelio — APPROVED** [review]
Looking good, just as we reviews on our call.

**Pull request merged**
